name: Build and release

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install
      - run: npm run build

      - run: 'echo "$GH_ACTION_SSH_KEY" > gh_actions_key'
        shell: bash
        env:
          GH_ACTION_SSH_KEY: ${{ secrets.GH_ACTION_SSH_KEY }}

      - name: SCP builded page to server
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          chmod 600 gh_actions_key
          ssh-keyscan orzel.me >> /home/runner/.ssh/known_hosts
          ssh -i gh_actions_key tomekkania@orzel.me "rm -rf /home/tomekkania/www && mkdir -p /home/tomekkania/www"
          scp -r  -i gh_actions_key ./public/* tomekkania@orzel.me:/home/tomekkania/www/
          ssh -i gh_actions_key tomekkania@orzel.me "sudo rm -rf /var/www/tomasz.kania.orzel.me/*; sudo cp -r /home/tomekkania/www/* /var/www/tomasz.kania.orzel.me/"

      - name: Setup IPFS
        id: ipfs_setup
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true

      - name: Add files to IPFS and pin on Infura
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
        shell: bash
        run: |
          export CID=$(ipfs add -r --cid-version 1 ./public | tail -1 | cut -d ' ' -f2)
          echo "$CID"
          sleep 20
          curl -X POST --connect-timeout 30 -m 40 "https://ipfs.infura.io:5001/api/v0/pin/add?arg=$CID" -u "$INFURA_PROJECT_ID:$INFURA_PROJECT_SECRET"
          echo "::set-output name=CID::$CID"

      - name: GCloud Auth
        uses: "google-github-actions/auth@v0"
        id: gcloud_auth
        with:
          workload_identity_provider: "projects/684338339288/locations/global/workloadIdentityPools/workload-pool/providers/workload-provider"
          service_account: "cloud-dns-service-account@agresso-pl-239805.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"
