name: Health Check 

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check with 3 attempts
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://tomasz.kania.orzel.me
          follow-redirect: yes
          max-attempts: 2
          retry-delay: 5s
